version: '3'

services:
  app:
    image: node:latest
    container_name: jsonp_practice
    tty: true
    volumes:
      - ./src:/src
    working_dir: '/src'
    ports:
      - '8080:3000'
    command: /bin/bash -c "npm install && node app.js"
